### ISSUE TITLE
Unable to create vm using guest_customization_cloud_init_custom_key_values

### ISSUE THREAD

**Issue by chandru-tkc** [nutanix/terraform-provider-nutanix#58]
**Describe the bug**
Unable to create a vm using guest_customization_cloud_init_custom_key_values 

**Expected behavior**
Able to create the vm with the attribute guest_customization_cloud_init_custom_key_values like below,
`guest_customization_cloud_init_custom_key_values = {
  "username" = "centos1"
  "password" = "nutanix/4u"
  
}
`

**Logs**
`panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: goroutine 84 [running]:
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/nutanix.getVMResources(0xc00036d810, 0xc000131110, 0x1ad85da, 0x2)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go:1465 +0x17bf
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/nutanix.resourceNutanixVirtualMachineCreate(0xc00036d810, 0x192aae0, 0xc0005b2b00, 0x24, 0x2416700)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go:774 +0x446
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4: github.com/terraform-providers/terraform-provider-nutanix/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000510bd0, 0xc000358730, 0xc0003febe0, 0x192aae0, 0xc0005b2b00, 0x100b601, 0xc00034fb80, 0x10bdcdc)
2019-05-07T17:30:55.845+1000 [DEBUG] plugin.terraform-provider-nutanix_v1.0.1_x4:       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-nutanix/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351`

**Versions (please complete the following information):**
 - Mojave OSX 
 - Terraform - v0.11.13
 - PE AOS 5.10.1, PC - 5.10.1.1
- Terraform provider version v1.0.1

**Comment by switchboardOp** [comment]
I'm having the same issue.

```terraform
resource "nutanix_virtual_machine" "node" {
 ...
  guest_customization_cloud_init_custom_key_values = {
    hostname = "ros1"
  }
...
```
Is causing `terraform apply` to crash with similar output to above.
 
- Mojave OSX
- Terraform - v0.11.14
- PE 5.10.3.2 LTS, PC - 5.10.3
- Terraform provider version v1.0.1

**Comment by UnreleasedCode** [comment]
Same here... Please fix or support a workaround
